# -*- coding: utf-8 -*-
"""DataPreparation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Pf2Dt8Z3DFAjdqGtIYLT2DljK8pLk-y
"""

import requests, re, json, bs4
import pandas as pd

r = requests.get('https://ntrs.nasa.gov/api/citations/search?abstract=the')
data = json.loads(re.search(r'(\{.*/api.*\})', r.text).group(1).replace('&q;','"'))

Abstract_list = []
ID_list = []
Title_list = []

for publi in data['results']:
    abstract = publi['abstract']
    ID = publi['id']
    Title = publi['title']
    Title_list.append(Title)
    ID_list.append(ID)
    Abstract_list.append(abstract)

dic_NTRS = {'Title': Title_list, 'ID': ID_list, 'Abstract': Abstract_list}
df_NTRS = pd.DataFrame.from_dict(dic_NTRS)
NTRS_Table = df_NTRS.to_csv(index=False)